# Generated by Django 6.0.4 on 2026-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pitches/photos/'),
        ),
    ]
