# Generated by Django 6.0.4 on 2026-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0003_pitch_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='photo',
        ),
        migrations.AddField(
            model_name='pitch',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
