# Generated by Django 6.0.4 on 2026-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_remove_pitch_photo_pitch_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='surface_type',
            field=models.CharField(blank=True, choices=[('NATURAL_GRASS', 'Натуральный газон'), ('SYNTHETIC_GRASS', 'Искусственный газон'), ('PARQUET', 'Паркет / Зал'), ('ASPHALT', 'Асфальт'), ('RUBBER', 'Резиновое покрытие'), ('SAND', 'Песок')], max_length=50, null=True),
        ),
    ]
