# Generated by Django 6.0.4 on 2026-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0005_alter_pitch_surface_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
