# Generated by Django 6.0.4 on 2026-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0006_pitch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Футбол'), ('BASKETBALL', 'Баскетбол'), ('PING_PONG', 'Пинг-понг'), ('VOLLEYBALL', 'Волейбол'), ('TENNIS', 'Большой теннис'), ('WORKOUT', 'Воркаут / Турники'), ('RUNNING', 'Бег'), ('CYCLING', 'Велоспорт'), ('YOGA', 'Йога'), ('PADEL', 'Падел-теннис'), ('CHESS', 'Шахматы'), ('CHECKERS', 'Шашки'), ('BOXING', 'Бокс / Единоборства'), ('SWIMMING', 'Плавание'), ('GYM', 'Тренажерный зал / Фитнес'), ('MULTI', 'Мультиспорт')], max_length=50),
        ),
    ]
