# Generated by Django 6.0.4 on 2026-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0007_alter_pitch_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Платная площадка'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за час'),
        ),
    ]
