# Generated by Django 6.0.4 on 2026-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0008_pitch_is_paid_pitch_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='fields_count',
            field=models.PositiveIntegerField(default=1, help_text='Количество независимых полей на площадке'),
        ),
    ]
