# Generated by Django 6.0.4 on 2026-06-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0009_pitch_fields_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
