# Generated by Django 6.0.4 on 2026-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0010_pitch_is_active_pitch_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='fields_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
