# Generated by Django 6.0.4 on 2026-06-21 10:42

from django.db import migrations

def copy_fields_count_to_breakdown(apps, schema_editor):
    Pitch = apps.get_model('pitches', 'Pitch')
    
    for pitch in Pitch.objects.all():
        if pitch.sport_type == 'MULTI':
            pitch.fields_breakdown = {'FOOTBALL': pitch.fields_count}
        else:
            pitch.fields_breakdown = {pitch.sport_type: pitch.fields_count}
            
        pitch.save(update_fields=['fields_breakdown'])

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        
        ('pitches', '0011_pitch_fields_breakdown'),
    ]

    operations = [
        migrations.RunPython(copy_fields_count_to_breakdown, reverse_code=reverse_copy),
    ]