# Generated by Django 6.0.4 on 2026-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0012_auto_20260621_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='fields_count',
        ),
    ]
