# Generated by Django 6.0.4 on 2026-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('PING_PONG', 'Ping Pong')], max_length=50)),
                ('max_players', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('external_chat_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
