# Generated by Django 6.0.4 on 2026-04-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='level',
            field=models.CharField(choices=[('ANY', 'Любой'), ('BEGINNER', 'Новичок'), ('AMATEUR', 'Любитель'), ('PRO', 'Профи')], default='ANY', max_length=20),
        ),
    ]
