# Generated by Django 6.0.4 on 2026-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sport_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
