# Generated by Django 6.0.4 on 2026-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='reset_pin_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
